### PR TITLE
menu icons changed according to heading

### PR DESCRIPTION
**Pull request by Aksgo**
I have changed the icons according to each heading. Please check the image below.
p1

### CODE REVIEW

**Comment by Alexandrbig1** [comment]
The icons is so big, and it not improve the webpage, by my opinion, cause now we have all different icons...can you resize them or maybe find icons similar to the context but at least be from the same bundle.

**Review by Alexandrbig1 — CHANGES_REQUESTED** [review]
The icons is so big, and it not improve the webpage, by my opinion, cause now we have all different icons...can you resize them or maybe find icons similar to the context but at least be from the same bundle. But, anyway thank you for contributing, and waiting for your changes

**Comment by Aksgo** [comment]
ohk, I am just a beginner in this, but thanks for guiding

**Comment by Alexandrbig1** [comment]
That's ok, thank you for contributing! You still can contribute, do some small changes, or improve some of them and pull request! Thank you!

**Pull request closed without merging**
